version: "3.8"
services:
  martian:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=3000
    stdin_open: true
    tty: true
    command: npm start
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
